development:
  adapter: postgresql
  encoding: unicode
  database: gametrader_development
  pool: 16

test:
  adapter: postgresql
  encoding: unicode
  database: gametrader_test
  pool: 16

production:
  adapter: postgresql
  encoding: unicode
  database: gametrader_production
  pool: 16
